export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const BOARD_LOADING = "BOARD_LOADING";
export const GET_BOARDS = "GET_BOARDS";
export const GET_DETAIL_POST = "GET_DETAIL_POST";
export const CLEAR_BOARD = "CLEAR_BOARD";
export const CREATE_BOARD = "CREATE_BOARD";
export const EDIT_BOARD = "EDIT_BOARD";
export const DELETE_BOARD = "DELETE_BOARD";
export const LIKE_BOARD = "LIKE_BOARD";
export const SAVE_BOARD = "SAVE_BOARD";

export const ADD_INGREDIENTS = "ADD_INGREDIENTS";
export const ADD_PROCEDURES = "ADD_PROCEDURES";
export const ADD_COOKTIME = "ADD_COOKTIME";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_PICTURE = "ADD_PICTURE";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const EDIT_USER = "EDIT_USER";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const GET_SAVED_POSTS = "GET_SAVED_POSTS";
export const GET_USER_POSTS = "GET_USER_POSTS";
export const GET_AVATAR = "GET_AVATAR";
export const CHANGE_AVATAR = "CHANGE_AVATAR";
